### ISSUE TITLE
use fixed ENV SOURCE_DATE_EPOCH but still not reproducible 

### ISSUE THREAD

**Issue by zny666** [inclavare-containers/rbi#5]
when i tried to reproducible build docker image for CDH, to fix the time i use `ENV SOURCE_DATE_EPOCH="315532800" ` in dockerfile, but the hash values are still different. I saved the image as tar file, and find the file in /blobs/sha256/ contains the system time, I have decompressed the file and then re compress it, and use `--mtime="1980-10-10"` to fix the time of tar file, but it doesn't work, as the difference is in the tile, as follows.
`{"architecture":"amd64","config":{"ExposedPorts":{"50000/tcp":{}},"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/bash"],"Volumes":{"/etc/confidential-data-hub.toml":{}},"Labels":{"org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.source":"https://github.com/inclavare-containers/confidential-data-hub","org.opencontainers.image.version":"22.04"}},"created":"2024-08-21T16:27:16.350259606+08:00","history":[{"created":"2024-06-27T20:10:10.528110614Z","created_by":"/bin/sh -c #(nop)  ARG RELEASE","empty_layer":true},{"created":"2024-06-27T20:10:10.566300625Z","created_by":"/bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH","empty_layer":true},{"created":"2024-06-27T20:10:10.606737029Z","created_by":"/bin/sh -c #(nop)  LABEL org.opencontainers.image.ref.name=ubuntu","empty_layer":true},{"created":"2024-06-27T20:10:10.638915467Z","created_by":"/bin/sh -c #(nop)  LABEL org.opencontainers.image.version=22.04","empty_layer":true},{"created":"2024-06-27T20:10:12.481980539Z","created_by":"/bin/sh -c #(nop) ADD file:d5da92199726e42da09a6f75a778befb607fe3f79e4afaf7ef5188329b26b386 in / "},{"created":"2024-06-27T20:10:12.703519218Z","created_by":"/bin/sh -c #(nop)  CMD [\"/bin/bash\"]","empty_layer":true},{"created":"2024-08-21T16:27:16.19011078+08:00","created_by":"LABEL org.opencontainers.image.source=https://github.com/inclavare-containers/confidential-data-hub","comment":"buildkit.dockerfile.v0","empty_layer":true},{"created":"2024-08-21T16:27:16.19011078+08:00","created_by":"COPY /usr/local/bin/ossfs /usr/local/bin/ossfs # buildkit","comment":"buildkit.dockerfile.v0"},{"created":"2024-08-21T16:27:16.252457371+08:00","created_by":"COPY /usr/bin/gocryptfs /usr/local/bin/gocryptfs # buildkit","comment":"buildkit.dockerfile.v0"},{"created":"2024-08-21T16:27:16.350259606+08:00","created_by":"COPY /usr/src/guest-components/target/x86_64-unknown-linux-gnu/release/confidential-data-hub /usr/local/bin/confidential-data-hub # buildkit","comment":"buildkit.dockerfile.v0"},{"created":"2024-08-21T16:27:16.350259606+08:00","created_by":"VOLUME [/etc/confidential-data-hub.toml]","comment":"buildkit.dockerfile.v0","empty_layer":true},{"created":"2024-08-21T16:27:16.350259606+08:00","created_by":"EXPOSE map[50000/tcp:{}]","comment":"buildkit.dockerfile.v0","empty_layer":true}],"os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:931b7ff0cb6f494b27d31a4cbec3efe62ac54676add9c7469560302f1541ecaf","sha256:26bde499dfc45eeb387da6285560efc6421c62ad07030d513ca143cd3e8f559a","sha256:94be37551b6f6e79f196b4bb5d051246f2e46f7f18bbf52af9daa2c1c0c0c725","sha256:ca205c583c1fab640708f33a239e0090f35258b891c97763b3ca9e1411ad15eb"]}}`
It seems like when build the image, the running time of each instruction in dockerfile is recorded, and the cached files are also retained, even if I use the `--no-cache` parameter.

**Comment by zny666** [comment]
I tried using the faketime tool to modify the system time, 
`
$ LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1 FAKETIME="2020-12-24 20:30:00" 
`
`
$ date
2020年 12月 24日 星期四 20:30:00 CST
`
and in the shell file, when i write 
`
CDH_COMMIT="bf7ccd301d3f50bfcb4cc9e38ae187141ce35072"
`
`
LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1 FAKETIME="2020-12-24 20:30:00"
`
`
sudo docker build --progress=plain --no-cache --build-arg CDH_COMMIT=${CDH_COMMIT} -t rbi-cdh:v9 .
`
then the github connection is terminated, 
`
fatal: unable to access 'https://github.com/confidential-containers/guest-components.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
`
and when i write
`LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1 FAKETIME="2020-12-24 20:30:00" /bin/bash -c 'docker build --progress=plain --no-cache --build-arg CDH_COMMIT=${CDH_COMMIT} -t rbi-cdh:v8 .'`
it can run well, but the image file still contains the real time, like
`
{"created":"2024-06-27T20:10:10.606737029Z","created_by":"/bin/sh -c #(nop)  LABEL org.opencontainers.image.ref.name=ubuntu","empty_layer":true},{"created":"2024-06-27T20:10:10.638915467Z","created_by":"/bin/sh -c #(nop)  LABEL org.opencontainers.image.version=22.04","empty_layer":true},{"created":"2024-06-27T20:10:12.481980539Z","created_by":"/bin/sh -c #(nop) ADD file:d5da92199726e42da09a6f75a778befb607fe3f79e4afaf7ef5188329b26b386 in / "},{"created":"2024-06-27T20:10:12.703519218Z","created_by":"/bin/sh -c #(nop)  CMD [\"/bin/bash\"]","empty_layer":true},{"created":"2024-08-24T10:39:40.600857951+08:00","created_by":"LABEL org.opencontainers.image.source=https://github.com/inclavare-containers/confidential-data-hub","comment":"buildkit.dockerfile.v0","empty_layer":true},{"created":"2024-08-24T10:39:40.600857951+08:00","created_by":"COPY /usr/local/bin/ossfs /usr/local/bin/ossfs # buildkit","comment":"buildkit.dockerfile.v0"},{"created":"2024-08-24T10:39:40.694336422+08:00","created_by":"COPY /usr/bin/gocryptfs /usr/local/bin/gocryptfs # buildkit","comment":"buildkit.dockerfile.v0"},{"created":"2024-08-24T10:39:40.854094242+08:00","created_by":"COPY /usr/src/guest-components/target/x86_64-unknown-linux-gnu/release/confidential-data-hub /usr/local/bin/confidential-data-hub # buildkit","comment":"buildkit.dockerfile.v0"},{"created":"2024-08-24T10:39:40.854094242+08:00","created_by":"VOLUME [/etc/confidential-data-hub.toml]","comment":"buildkit.dockerfile.v0","empty_layer":true},{"created":"2024-08-24T10:39:40.854094242+08:00","created_by":"EXPOSE map[50000/tcp:{}]","comment":"buildkit.dockerfile.v0","empty_layer":true}]
`
and now i try to look up the date,
`$ date
2020年 12月 24日 星期四 20:30:00 CST`
it's still the time i changed. And it cant connect to github.
Now i guess the time may be get by the internet? or how to solve the problem: how to connect github when using faketime?

**Comment by 1570005763** [comment]
@zny666  I think libfaketime will affect TLS connection. For example, setting the time manually could result in certificate verification failures. So it is better not involving network operation when using libfaketime. You can try to pre-download related repository, and run `docker build` with libfaketime afterwards.

**Comment by zny666** [comment]
I pre-download the crates( run it locally and get the cache, but a little big, 1.4G), move it into the image to replace the original download command, and set the cargo cache. 
`RUN mkdir /usr/src/.cargo`
`ENV CARGO_HOME=/usr/src/.cargo`
`COPY ./.cargo /usr/src/.cargo`
Now it can build the image correctly with libfaketime, but the date in image file is still the real time, 
`{"created":"2024-06-27T20:10:12.703519218Z","created_by":"/bin/sh -c #(nop)  CMD [\"/bin/bash\"]","empty_layer":true},{"created":"2024-08-25T11:28:47.975550739+08:00","created_by":"LABEL org.opencontainers.image.source=https://github.com/inclavare-containers/confidential-data-hub","comment":"buildkit.dockerfile.v0","empty_layer":true},{"created":"2024-08-25T11:28:47.975550739+08:00","created_by":"COPY /usr/local/bin/ossfs /usr/local/bin/ossfs # buildkit","comment":"buildkit.dockerfile.v0"}`
I guess that docker may get time from the docker official website? And I have no idea to solve it.

**Comment by 1570005763** [comment]
@zny666 There are two things you can try.
1. Try to run `LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1 FAKETIME="2020-12-24 20:30:00" /bin/bash -c 'date'` to see whether libfaketime works, since your build command after `/bin/bash -c` runs in a new bash shell. If it does work, please try the next one.
2. This could be because libfaketime does not fully control all the necessary timestamps, especially with regard to Docker’s internal mechanisms. Because internal components of Docker, such as BuildKit, may bypass the influence of libfaketime. If this is the case, please refer to the usage of [SOURCE_DATE_EPOCH](https://reproducible-builds.org/docs/source-date-epoch/). In the 'Dockerfile' section, specifically in the 'Scope' part, it explains how to fix the `created timestamp` in the OCI Image Config.

**Comment by zny666** [comment]
Thank you, it works by using buildkit and rewrite the SOURCE_DATE_EPOCH.
