### ISSUE TITLE
After package updates itself, older versions of the package cannot be installed through apt

### ISSUE THREAD

**Issue by zny666** [inclavare-containers/rbi#6]
A week ago, the default version of OpenSSL was 3.0.2-0 Ubuntu 1.17, but now OpenSSL in the apt source has been updated to 3.0.2-0 Ubuntu 1.18. At this point, when I install `apt-get install - y openssl=3.0.2-0 ubuntu1.17` by specifying the version, it will display Version `'3.0.2-0 ubuntu1.17' for 'openssl' was not found`. After reviewing the information, once the software package is upgraded to a new version, older versions of the software package will be removed from the APT cache and repository, [link](https://linux.cn/article-14760-1.html). Now, I try to use `add-apt-repository ppa:kmix/openssl` to add openssl of fix version, and it works.

**Comment by zny666** [comment]
I try not to execute apt update as well, but it will cause apt to be unable to obtain the new package list and install packages. `add-apt-repository ppa:kmix/openssl` works but I don't know if the provider will change the version of the package provided by the connection.

**Comment by 1570005763** [comment]
@zny666  For now, I believe that obtaining a specific version of OpenSSL by adding a PPA is a viable solution to this problem. If you are genuinely concerned about the stability of the PPA, you could also consider obtaining the source code from [OpenSSL](https://openssl-library.org/source/old/3.0/index.html) and compiling it manually.
